### ISSUE TITLE
TCB는 어디에 있을까요? 

### ISSUE THREAD

**Issue by worldii** [ZI-won-ZONE-ha/CS_JONGJIBU#2]
TCB의 위치가 궁금합니다!

**Comment by jjiwoning** [comment]
PCB 안에 포함됩니다

**Comment by worldii** [comment]
https://teraphonia.tistory.com/802
https://www.cs.fsu.edu/~baker/opsys/notes/threads.html

확실하진 않은데 PCB와 따로 두는거 같지 않나요? 
![image](https://github.com/ZI-won-ZONE-ha/CS_JONGJIBU/assets/87687210/a74c24a6-fdba-4474-99ab-582ed99692cf)

**Comment by jjiwoning** [comment]
https://inpa.tistory.com/entry/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BB-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4-%E2%9A%94%EF%B8%8F-%EC%93%B0%EB%A0%88%EB%93%9C-%EC%B0%A8%EC%9D%B4#tcb_thread_control_block

데이터 저장은 따로 두는게 맞는거 같고 PCB 내부에 자신의 Thread에 대한 TCB로 접근할 수 있는 주소 값을 저장하는거 같아요

**Comment by worldii** [comment]
개굳
