### ISSUE TITLE
[Real-My-SQL] Chapter5 메타 데이터 락 예제에 대한 질문

### ISSUE THREAD

**Issue by worldii** [ZI-won-ZONE-ha/CS_JONGJIBU#6]
# 질문 
P166의 중반부에 있는 예제에서 '트랜젝션을 autocommit으로 실행(BEGIN 이나 START TRANSACTION으로 실행하면 안됨)' 라고 적혀있는데 왜 그럴까요? 
start commit 을 쓰면 안되는 이유가 있을까요? 
# 참고 자료 
real mySQL P.166

**Comment by jjiwoning** [comment]
저도 이 부분이 궁금해서 찾아봤는데 공식 문서에서 table lock과 begin transaction에 대해서 이렇게 알려주네요

<img width="1014" alt="image" src="https://github.com/ZI-won-ZONE-ha/CS_JONGJIBU/assets/88527476/61b97187-a5f1-4c96-964d-fd870f8983ed">

<img width="979" alt="image" src="https://github.com/ZI-won-ZONE-ha/CS_JONGJIBU/assets/88527476/25071e9e-1963-49c0-b0bb-ebd0df3c410b">

start transaction으로 인해 table lock이 unlock되는 경우를 막고자 autocommit = 0로 시작하지 않았을까 생각해봅니다.

참고 링크
https://dev.mysql.com/doc/refman/5.7/en/lock-tables.html

**Comment by worldii** [comment]
같은 예제에서 궁금한 점이 또 생겼는데,
1. 메타 데이터 락은 묵시적으로 실행될 떄 어떤 락(readlock, writelock) 이 걸릴까요?
2. access_log는 쓰기 잠금을 하는 것은 알겠는데 왜 access_new_log 또한 쓰기 잠금을 하는 걸까요? 
(이전 페이지에서는 여러개 쓰레드 동시 돌릴려고 쓰기 잠금 안걸음)
3. 테이블 락이 걸릴 때, 메타 데이터 락도 걸린다.
<img width="1150" alt="image" src="https://github.com/ZI-won-ZONE-ha/CS_JONGJIBU/assets/87687210/8b6debe3-de2d-4ceb-a00e-179abb9ee1a3">

**Comment by worldii** [comment]
해----결 
디스커션에 올려놓겠습니다.
